# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryy/Projects/untamo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryy/Projects/untamo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/bryy/.pico-sdk/cmake/v3.31.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryy/Projects/untamo/CMakeFiles /home/bryy/Projects/untamo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryy/Projects/untamo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_library

# Build rule for target.
bs2_default_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_library
.PHONY : bs2_default_library

# fast build rule for target.
bs2_default_library/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default_library.dir/build.make pico-sdk/src/rp2350/boot_stage2/CMakeFiles/bs2_default_library.dir/build
.PHONY : bs2_default_library/fast

#=============================================================================
# Target rules for targets named cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# Build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cyw43_driver_picow_cyw43_bus_pio_spi_pio_h
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# fast build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build.make pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast

#=============================================================================
# Target rules for targets named pico_status_led_ws2812_pio_h

# Build rule for target.
pico_status_led_ws2812_pio_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pico_status_led_ws2812_pio_h
.PHONY : pico_status_led_ws2812_pio_h

# fast build rule for target.
pico_status_led_ws2812_pio_h/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/pico_status_led/CMakeFiles/pico_status_led_ws2812_pio_h.dir/build.make pico-sdk/src/rp2_common/pico_status_led/CMakeFiles/pico_status_led_ws2812_pio_h.dir/build
.PHONY : pico_status_led_ws2812_pio_h/fast

#=============================================================================
# Target rules for targets named untamo

# Build rule for target.
untamo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 untamo
.PHONY : untamo

# fast build rule for target.
untamo/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/untamo.dir/build.make src/CMakeFiles/untamo.dir/build
.PHONY : untamo/fast

#=============================================================================
# Target rules for targets named Config

# Build rule for target.
Config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Config
.PHONY : Config

# fast build rule for target.
Config/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/Config/CMakeFiles/Config.dir/build.make libs/oled/Config/CMakeFiles/Config.dir/build
.PHONY : Config/fast

#=============================================================================
# Target rules for targets named LCD

# Build rule for target.
LCD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LCD
.PHONY : LCD

# fast build rule for target.
LCD/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/LCD/CMakeFiles/LCD.dir/build.make libs/oled/LCD/CMakeFiles/LCD.dir/build
.PHONY : LCD/fast

#=============================================================================
# Target rules for targets named Infrared

# Build rule for target.
Infrared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Infrared
.PHONY : Infrared

# fast build rule for target.
Infrared/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/Infrared/CMakeFiles/Infrared.dir/build.make libs/oled/Infrared/CMakeFiles/Infrared.dir/build
.PHONY : Infrared/fast

#=============================================================================
# Target rules for targets named OLED

# Build rule for target.
OLED: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OLED
.PHONY : OLED

# fast build rule for target.
OLED/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/OLED/CMakeFiles/OLED.dir/build.make libs/oled/OLED/CMakeFiles/OLED.dir/build
.PHONY : OLED/fast

#=============================================================================
# Target rules for targets named Icm20948

# Build rule for target.
Icm20948: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Icm20948
.PHONY : Icm20948

# fast build rule for target.
Icm20948/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/Icm20948/CMakeFiles/Icm20948.dir/build.make libs/oled/Icm20948/CMakeFiles/Icm20948.dir/build
.PHONY : Icm20948/fast

#=============================================================================
# Target rules for targets named GUI

# Build rule for target.
GUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUI
.PHONY : GUI

# fast build rule for target.
GUI/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/GUI/CMakeFiles/GUI.dir/build.make libs/oled/GUI/CMakeFiles/GUI.dir/build
.PHONY : GUI/fast

#=============================================================================
# Target rules for targets named Fonts

# Build rule for target.
Fonts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fonts
.PHONY : Fonts

# fast build rule for target.
Fonts/fast:
	$(MAKE) $(MAKESILENT) -f libs/oled/Fonts/CMakeFiles/Fonts.dir/build.make libs/oled/Fonts/CMakeFiles/Fonts.dir/build
.PHONY : Fonts/fast

#=============================================================================
# Target rules for targets named pulse_lib

# Build rule for target.
pulse_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pulse_lib
.PHONY : pulse_lib

# fast build rule for target.
pulse_lib/fast:
	$(MAKE) $(MAKESILENT) -f libs/pulse/CMakeFiles/pulse_lib.dir/build.make libs/pulse/CMakeFiles/pulse_lib.dir/build
.PHONY : pulse_lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bs2_default_bin"
	@echo "... cyw43_driver_picow_cyw43_bus_pio_spi_pio_h"
	@echo "... pico_status_led_ws2812_pio_h"
	@echo "... Config"
	@echo "... Fonts"
	@echo "... GUI"
	@echo "... Icm20948"
	@echo "... Infrared"
	@echo "... LCD"
	@echo "... OLED"
	@echo "... bs2_default"
	@echo "... bs2_default_library"
	@echo "... pulse_lib"
	@echo "... untamo"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

